### ISSUE TITLE
Overview of hosting server

### ISSUE THREAD

**Issue by ariel1985** [ariel1985/aipages#14]
https://www.bluehost.com/special/homenew?clickid=zuf3Mn1SyxyPUXW2AjwdYzVdUkFUJp31Vyc2Vo0&irgwc=1&pb=affiliate_promo&irpid=159047&utm_medium=affiliate&utm_affiliate=cnetwebhosting&utm_affiliate_sys=IR&siteID=46095037&iradid=795082&utm_source=IR&utm_campaign=CNET%20Media%20Inc.&channelid=P61C46097236S645N0B2A1D0E0000V100 2$

https://www.hostgator.com/web-hosting

linode

**Comment by ariel1985** [comment]
@ozsoffy please add affiliate details for hosting

**Comment by ozsoffy** [comment]
My affiliate account not generate code anymore. 
we can use whatever you want...
